name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: supplypike/setup-bin@v3
      with:
        uri: "https://github.com/astral-sh/uv/releases/download/0.4.9/uv-x86_64-unknown-linux-gnu.tar.gz"
        name: "uv"
        version: "0.4.9"
        subPath: uv-x86_64-unknown-linux-gnu

    - name: Install dependencies
      run: make .venv

    - name: Run check
      run: make check
